name: Build LaTeX Document with Docker - Trama

on: [push]

jobs:
  build_latex_container:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: test docker
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
    - name: test working dir
      run: (ls $PWD)
    - name: compile Guide
      run: latexmk guide.tex
