name: Build LaTeX Document with Docker

on: [workflow_dispatch]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t latex-project .

    - name: Run Container
      run: docker run -d --name latex-compile-container latex-project tail -f /dev/null

    - name: Create Output Directory in Container
      run: docker exec latex-compile-container mkdir -p /usr/src/app/output

    - name: Compile LaTeX Document
      run: |
        docker exec latex-compile-container latexmk -pdf -output-directory=/usr/src/app/output /usr/src/app/latex-project/example_paper/lamonaca.tex

    - name: Copy PDF from Container
      run: docker cp latex-compile-container:/usr/src/app/output/lamonaca.pdf .

    - name: Copy Log from Container
      run: docker cp latex-compile-container:/usr/src/app/output/lamonaca.log .

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: lamonaca.pdf

    - name: Upload Log as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compile-log
        path: lamonaca.log
