name: Build LaTeX Document with Docker - Trama

on: [workflow_dispatch]

jobs:
  compile_in_latex_container_trama:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: test docker
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
    - name: test working dir
      run: (ls $PWD)
    - name: compile Guide
      run: latexmk -pdf guide.tex
