name: Create Release ZIP

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags (e.g., v1.0, v2.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra biber texlive-fonts-extra

      - name: Compile imeko-bare-article.tex
        run: |
          cp -r class/. bare\ article\ template
          cd "bare article template"
          pdflatex imeko-bare-article.tex
          bibtex imeko-bare-article
          pdflatex imeko-bare-article.tex
          pdflatex imeko-bare-article.tex
          mv imeko-bare-article.pdf ../

      - name: Compile guide.tex
        run: |
          cd guide
          pdflatex guide.tex
          pdflatex guide.tex
          mv guide.pdf ../

      - name: Prepare release directory
        run: |
          mkdir release
          cp -r class release/
          cp -r "bare article template" release/
          cp -r "Original Acta IMEKO template" release/
          cp guide.pdf release/bare\ article\ template/
          cp imeko-bare-article.pdf release/bare\ article\ template/
          cp -r class/* release/bare\ article\ template/

      - name: Create ZIP archive
        run: zip -r imeko_acta_release.zip release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: imeko_acta_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
